### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by qengine13** [anshuUnity/whatsapp-clone#5]
This doesnt seem to work for me.. when running server i get 👍 
`Traceback (most recent call last):
  File "/Users/avichayil/Documents/whatsapdemo/whatsapp-clone/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/avichayil/Documents/whatsapdemo/whatsapp-clone/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/avichayil/Documents/whatsapdemo/whatsapp-clone/chats/views.py", line 16, in chatPage
    user_obj = User.objects.get(username=username)
  File "/Users/avichayil/Documents/whatsapdemo/whatsapp-clone/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/avichayil/Documents/whatsapdemo/whatsapp-clone/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.User.DoesNotExist: User matching query does not exist.`

**Comment by anshuUnity** [comment]
Add try except statement to catch exception
